### ISSUE TITLE
Database tidak ditemukan

### ISSUE THREAD

**Issue by adedarma17** [ilhamdsofyan/core-irbac#5]
Apakah backup databasenya tidak ada di upload, sepuh?

**Comment by ilhamdsofyan** [comment]
> Apakah backup databasenya tidak ada di upload, sepuh?

Niatnya mau dibuat migration-nya. Tapi belum ada waktu luang

**Comment by adedarma17** [comment]
Apakah bisa di upload, sepuh?
File SQL nya

**Comment by ilhamdsofyan** [comment]
> Apakah bisa di upload, sepuh? File SQL nya

Done, cek lagi di root directory
